### ISSUE TITLE
How to set contant speed

### ISSUE THREAD

**Issue by jariesdev** [EvodiaAut/vue-marquee-text-component#19]
How to apply consistent speed regardless of content length?

**Comment by EvodiaAut** [comment]
Would that [answer](https://github.com/EvodiaAut/vue-marquee-text-component/issues/5#issuecomment-444243395) your question?

**Comment by jariesdev** [comment]
Sorry but no answer yet. We have a container which content text change every time. Setting to specic speed sometime make the marquee too slow or too fast so I need a way to make the speed consistent regardless of how long the data was.

**Comment by EvodiaAut** [comment]
In my link the content gets a fixed width and should solve the problem as the speed is now constant.
Alternatively you can create an example?

**Comment by jariesdev** [comment]
Sorry for late response, bit busy lately but here is the example of what I mean.

https://jsfiddle.net/jariesdev/vuwxgrfn/

As you notice same configuration but different content. You can see that speed is not consistent both marquee.

**Comment by EvodiaAut** [comment]
Here is an example https://jsfiddle.net/0ufmqw2x
The duration depends on the width, to make the width equal I set a div with the same width. (See my first answer)

**Comment by jariesdev** [comment]
Yes, this what i wanted except there should be no white space which
"repeat" option suppose to do right?

**Comment by kinanson** [comment]
I am set fixed width that will apply  consistent speed.
But too long word will be multi line.So this issue not realy resolve.
Can help to add feature like as "consisten=true" ??

**Comment by EvodiaAut** [comment]
It is important to be sure that it is a pure CSS based solution.
I do not want to use JS to calculate the width.

The width indicates the speed and can be adjusted with the property duration.
