### ISSUE TITLE
it's shaking a bit

### ISSUE THREAD

**Issue by diomed** [EvodiaAut/vue-marquee-text-component#2]
when it's going slower it's a bit shaky. 
do you notice?

**Comment by EvodiaAut** [comment]
there are many factors can you send me a example?

**Comment by diomed** [comment]
it's seen in first demo example. it's going slowly, but it's shaking a bit, doesn't run smooth.

**Comment by EvodiaAut** [comment]
On me it's works fine (and i also notice too the minimal [screen tearing](https://en.wikipedia.org/wiki/Screen_tearing))

As I have already said there are many factors (your device, your monitor, **[screen tearing](https://en.wikipedia.org/wiki/Screen_tearing)**)
I don't can resolve your issue sorry
