### ISSUE TITLE
how to use in Nuxt.js

### ISSUE THREAD

**Issue by plategea** [EvodiaAut/vue-marquee-text-component#20]
hi i want use vue-marquee-text-componnet in nuxt

**Comment by EvodiaAut** [comment]
Hi @plategea,

i have no experience with Nuxt.js.
Is there an error message?

**Comment by mattgilbertnet** [comment]
The error is "document is not defined". Nuxt appears to be running code on the server that it shouldn't. Wrapping wherever document is called with `if (process.client) {...}` might be the fix.

**Comment by katerlouis** [comment]
I tried using the plugin only on client like this:

```js
// nuxt.config.js
plugins: [
  '@/plugins/components.client.js',
]
```

```js
// src/plugins/components.client.js
import Vue from 'vue';
import MarqueeText from 'vue-marquee-text-component';

export default (context, inject) => {
  Vue.component('MarqueeText', MarqueeText);
};
```

But this results in a mismatch between server-side virtual DOM and client-side rendered content. 

![image](https://user-images.githubusercontent.com/1983382/143861053-a08b2b0c-0a1b-4d15-92c3-7adc78743fbb.png)

**Comment by veebull** [comment]
I had the same problem. I have Nuxt2. The problem is in version. I used the latest version of plugin vue-marquee-text for vue3, but need for vue2
So use version for vue2 (branch https://github.com/EvodiaAut/vue-marquee-text-component/tree/v1)
downgrade to v1.2.0

**Comment by resuta566** [comment]
> I tried using the plugin only on client like this:
> 
> ```js
> // nuxt.config.js
> plugins: [
>   '@/plugins/components.client.js',
> ]
> ```
> 
> ```js
> // src/plugins/components.client.js
> import Vue from 'vue';
> import MarqueeText from 'vue-marquee-text-component';
> 
> export default (context, inject) => {
>   Vue.component('MarqueeText', MarqueeText);
> };
> ```
> 
> But this results in a mismatch between server-side virtual DOM and client-side rendered content.
> 
> ![image](https://user-images.githubusercontent.com/1983382/143861053-a08b2b0c-0a1b-4d15-92c3-7adc78743fbb.png)

I also have mismatch childnodes. Did you fix it?

**Comment by KaiReichart** [comment]
For anyone coming here using nuxt 3, this is how I got it to work:

**Create a plugin in ``plugins/vue-marquee-text-component.js`**

```js
import MarqueeText from 'vue-marquee-text-component';

export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.component('MarqueeText', MarqueeText);
})
```

**Load plugin in `nuxt.config.ts`**
```ts
export default defineNuxtConfig({

    plugins: [
        {
            src: '@/plugins/vue-marquee-text.js', mode: 'client'
        },
    ],

})

```

**Now you can use `<MarqueeText>...</MarqueeText>` directly in your component. BUT you must wrap it in `<client-only></client-only>`**
```vue
<template>
  <div>
    <client-only>
      <MarqueeText>
        Text
      </MarqueeText>
    </client-only>
  </div>
</template>

```
