### ISSUE TITLE
document is not defined Error

### ISSUE THREAD

**Issue by hamedsrk** [EvodiaAut/vue-marquee-text-component#23]
greeting
i want to use this package in nuxt and i got this error message 

> document is not defined

`  var styleElement = document.querySelector('style[' + ssrIdKey + '~="' + obj.id + '"]')
`
do you have any solution ?

**Comment by kylewelsby** [comment]
if you're using this with nuxt.js, consider defidining this as a plugin and omitting it from server side rendering. 

```javascript
// ./plugins/v-marquee-text.js
import Vue from 'vue'
import MarqueeText from 'vue-marquee-text-component'

// eslint-disable-next-line vue/component-definition-name-casing
Vue.component('marquee-text', MarqueeText)
```

in your nuxt.js configuration

```javascript
// ./nuxt.config.js

{
  //...
  plugins: [
    { ssr: false, src: './plugins/v-marquee-text.js' }
  ],
  //...
}
```

**Comment by EvodiaAut** [comment]
Sorry @hamedsrk I don't use nuxt.
@kylewelsby thank you for your support
