### ISSUE TITLE
V2 (Vue3) 

### ISSUE THREAD

**Issue by EvodiaAut** [EvodiaAut/vue-marquee-text-component#25]
## Implement preview:

```html
<marquee-text v-model="5">
  Lorem ipsum dolor sit amet, consetetur sadipscing elitr...
</marquee-text>
```

## V-Model:
|Type|Default|Description
|-|-|-|
|Number|2|Number of repeat the Slot (It's important for to short content)

## Props
|Prop|Type|Default|Description
|-|-|-|-|
|duration|Number|15|Animation Duration
|paused|Boolean|false|The property specifies whether the animation is running or paused
|reverse|Boolean|false|Set animation-direction to reverse

## Optimise
* Code
* Style module again?

## New
* Add transform:translateY

**Comment by jakubmirejovsky** [comment]
Any news on Vue 3 version? :)

**Comment by EvodiaAut** [comment]
Hi @jakubmirejovsky, 

I just started a project with Vue3.
I would like to gain some experience before I implement the component in Vue3.

**Comment by leightonhughes** [comment]
Hey @EvodiaAut, I've started to move to Vue 3 as well. Any more news on a Vue 3 version, or an alternative that you could recommend? Cheers!

**Comment by EvodiaAut** [comment]
Hi @leightonhughes,

i hope by the end of this month I will have gained a lot of experience.
Then I will start with Vue3, but pull requests are always welcome.

**Comment by crutchcorn** [comment]
Got the library working 100% in Vue 3 in PR #40. No functionality has been removed, no API changes (outside of Vue 2 -> 3) and minimal logic changes (simply porting to Vue 3's API changes)

**Comment by EvodiaAut** [comment]
I have created a new branch `develop`.

* Eslint was included (+ my Config)
* { vnode: key } was removed (on hover the component was always reloaded, like when adding an event)
* prop.reverse was just empty, had to be fixed by actually checking if boolean !== false
* attrs.css had to be removed, because passed classes were output twice
![remove_attrs_class](https://user-images.githubusercontent.com/22764492/135286480-4d7a158d-6862-4bfa-842d-631b92d29686.png)


So far it looks like the migration was successful.
There are some common things that I don't quite understand.

**Comment by crutchcorn** [comment]
Seems like most top-level props (`key`, `style`, event binds) are passed to the root HTML element when using `h`

I admittedly haven't build a functional component in Vue 3 before

**Comment by EvodiaAut** [comment]
@crutchcorn you have helped me a lot!
**Thank you very much!**

I will now try to test and release the v2!

**Comment by crutchcorn** [comment]
Heads up: I seem to have issues with TS usage in v2. My bad. I'll fix that right now

**Comment by EvodiaAut** [comment]
So that props can also be deposited and $style does not cause any problems, I have rewritten the whole thing as a [Render Function](https://v3.vuejs.org/guide/render-function.html#render-functions). Unfortunately, [Functional Component](https://v3.vuejs.org/guide/render-function.html#jsx) was not suitable for this or it is intended as a very simple component (also something new for me^^).

- Thanks again for your support!

**Comment by crutchcorn** [comment]
TS error fixed in #25

**Comment by EvodiaAut** [comment]
@crutchcorn done, 2.0.1, can you check?

**Comment by crutchcorn** [comment]
Yup! Works in my app now

**Comment by mzy2240** [comment]
So I guess the v2 does not work with Vue2, right?

**Comment by crutchcorn** [comment]
@mzy2240 this should be correct, yes

**Comment by EvodiaAut** [comment]
@mzy2240 See Branch V1 (V1 = Vue2): https://github.com/EvodiaAut/vue-marquee-text-component/tree/v1
