### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'duration' of undefined

### ISSUE THREAD

**Issue by zplits** [EvodiaAut/vue-marquee-text-component#27]
Hello, first of all thank you for your very useful component.

I'm using it with Laravel 8 with InertiaJS + Vue 3.

I tried to use it but it get this error:
In developer Console i get the following: 
- Uncaught (in promise) TypeError: Cannot read property 'duration' of undefined.
- [Vue warn]: Unhandled error during execution of render function

By the way i tried to use it inside a component, hence i followed your instruction here:
```
// Tickers.vue
import MarqueeText from 'vue-marquee-text-component'

export default {
  name: 'Tickers',
  components: {
    MarqueeText
  }
}
```

Hope you can help me. 

Thank you.

**Comment by EvodiaAut** [comment]
Hi @zplits,

the problem is that the component is currently only for vue2.
**See #25**

I will try to implement it for VueJs3 this month.

**Comment by zplits** [comment]
Hi @EvodiaAut, thank you for your reply.

Alright, good luck on your endeavors.
