### ISSUE TITLE
How to make text start rolling from the right side of the component?

### ISSUE THREAD

**Issue by nilopaim** [EvodiaAut/vue-marquee-text-component#29]
How to do this?

**Comment by EvodiaAut** [comment]
Hi @nilopaim,

you can use the property `reverse` ?

**Comment by nilopaim** [comment]
Not exactly.

I need the text "coming" from the right side towards the left side, even when the text is smaller than the container.

Something like the rollup on the lower part of the screen, as can be seen on TV (CNN and others).

**Comment by EvodiaAut** [comment]
`When the text is smaller than the container` you need the property `repeat`.
See area [To small content](https://evodiaaut.github.io/vue-marquee-text-component/).

**Comment by nilopaim** [comment]
Oh, I see it now. 

By the way, excelent piece of software. Congratulations.

Thanks a lot.
