### ISSUE TITLE
have some advice

### ISSUE THREAD

**Issue by NoSugarCoffee** [EvodiaAut/vue-marquee-text-component#30]
I tried this component. it works normally, but why the text start rolling on the left of screen rather than right when use the default reverse props.

The means like following:

now status:
..................................
this is text
..................................

why not do like this ? 
..................................
 &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;   &nbsp; &nbsp;                                                                                  this is te
..................................

Thanks

**Comment by EvodiaAut** [comment]
Hi @NoSugarCoffee,

you could try to use a placeholder in front of the text?

**Comment by NoSugarCoffee** [comment]
I know that , but a little trick.

Thanks for your response.
