### ISSUE TITLE
add margin-prop

### ISSUE THREAD

**Issue by maltegrosse** [EvodiaAut/vue-marquee-text-component#37]
Hi, great plugin!
it would be nice to dynamic add some margin (or other whitespace-workaround) to avoid that the last letter is glued to the first one....
e.g.: 
before: TextTextText
after: Text Text Text
workaround 
```
.marquee-text-text{
  margin-right: 10px;
}
```

**Comment by EvodiaAut** [comment]
Only the user decides what the content should look like, not the component.

You can add global margin by class `.marquee-text-text` or 
```
<marquee-text>
  <div class="margin-class">Lorem ipsum dolor...</div>
</marquee-text>
```
