### ISSUE TITLE
No reactivity

### ISSUE THREAD

**Issue by hamidhosseini** [EvodiaAut/vue-marquee-text-component#4]
I'm trying to display some text inside the component which is going to change based on user's selection. The problem is, the component shows the data the first time the user selects something but it doesn't react if the user changes the selection.

This is my code for the template

>           
            <div class="col col-md-3" v-if="track">
                <div class="row">
                    <div class="col-2" @click="$router.push('/player')">
                        <a class="btn btn-controls align-self-center">
                            <i class="material-icons" style="color: white; font-size: 2em; margin-right: 10px; padding: 5px;">keyboard_arrow_up</i>
                        </a>
                    </div>
                    <div class="col-8 align-self-center text-left" @click="$router.push('/player')" >
                        <marquee-text :repeat="10">
                            //This has no reactivity
                            {{track.title}} - {{track.artist}}
                        </marquee-text>

                        // This works fine.
                        <div>{{track.title}} - {{track.artist}}</div>
                    </div>
                    <div class="col-2 align-self-center text-right d-block d-sm-none">
                        <a class="btn btn-controls" v-show="isPlaying" @click="pauseTrack()" >
                            <i class="material-icons" style="color: white; font-size: 2em; margin-right: 10px;">pause_circle_outline</i>
                        </a>
                        <a class="btn btn-controls align-self-center" v-show="!isPlaying" @click="resumeTrack()" >
                            <i class="material-icons" style="color: white; font-size: 2em; margin-right: 10px;">play_circle_outline</i>
                        </a>
                    </div>
                </div>
            </div>

I don't get any errors as well. Everything seems fine beside the fact that it doesn't work.

**Comment by EvodiaAut** [comment]
That's absolutely true.
The Problem is the component need a reload.

Now you can use in v1.1.1 the property :key="track.id" for reload the component
See https://codesandbox.io/s/rlqnjy8rpn
```html
<marquee-text :key="track.id" :repeat="10">
  //This has no reactivity
  {{track.title}} - {{track.artist}}
</marquee-text>
```

**Comment by hamidhosseini** [comment]
Thanks, it's working now. Just updated the package and added the key attribute. Everything is working fine now.  Oh and thanks for the great component. Tried everything myself. Couldn't get it to work but this was exactly what I was looking for.

**Comment by EvodiaAut** [comment]
You are welcome
When the component is public send me a url i like to see the components in action
