### ISSUE TITLE
Error in render: "TypeError: Cannot read properties of undefined (reading 'duration')"

### ISSUE THREAD

**Issue by ayoub-lwela** [EvodiaAut/vue-marquee-text-component#43]
![1](https://user-images.githubusercontent.com/36998905/138062903-0977ae3b-66f5-46b1-bdd0-e8809719ab78.PNG)

**Comment by adrianhand** [comment]
you will get this if you are using the vue-3 build on a vue-2 project.

If you're using vue-2, try

npm install vue-marquee-text-component@1.2.0

**Comment by EvodiaAut** [comment]
@ayoub-lwela have you tried with V1?
