### ISSUE TITLE
Text speed is not constant

### ISSUE THREAD

**Issue by kimyearho** [EvodiaAut/vue-marquee-text-component#5]
![image](https://user-images.githubusercontent.com/17153380/49458881-1c7f7080-f831-11e8-8265-05b85545e79b.png)

Example Video
https://youtu.be/zxPnlSx8TSk

Hi,
I am making music programs. You are using a module in a playlist. However, the text speed is not constant. I gave duration = "17", but the speed of each item may be the same or different. Is there something I've done wrong?

Thanks.

**Comment by EvodiaAut** [comment]
The duration depends from content length.
You can add `zaudio_songtitle` a fix width i think thats resolve your problem?

**Comment by kimyearho** [comment]
![image](https://user-images.githubusercontent.com/17153380/49492401-70bf3a80-f89b-11e8-9a13-f70690ad4bfa.png)

If you divide the size by 2 in the duration option, the speed remains the same.
This seems to be enough. Thanks

**Comment by EvodiaAut** [comment]
Your solution works but its not really exactly https://codesandbox.io/s/kopmm75np5
I mean this solution https://codesandbox.io/s/rmrwqrqrv4

P.S.:
I think the `&nbsp;` is a placeholder on start to see the title?
You can use the property `:paused` and set this with a timeout function.

**Comment by kimyearho** [comment]
Quick support Thank you.
The solution you presented is also very good. Thank you very much for providing a good module!
