### ISSUE TITLE
Marquee 2.0.1 stopped running on Vue 3.2.33/Node 16.14.2

### ISSUE THREAD

**Issue by mickey-bimlive** [EvodiaAut/vue-marquee-text-component#51]
I recently upgraded to the mentioned newest Vue 3 and Node level, and marquee stopped running. It shows the text , but is paused even with paused prop absent or set to true. Means the text is displayed, but not moved from right to left. No errors in logs.

**Comment by EvodiaAut** [comment]
@mickey58github 

I have just tested it with the version vue@3.2.33.
It runs without problems, unfortunately I don't notice anything?

**Comment by mickey-bimlive** [comment]
hmm, in my case it is embedded in a larger application, so I don't have a simpler testcase.  It doesn't show any errors in the log, the text is just paused since the upgrade. As a workaround, I replaced it by https://github.com/megasanjay/vue3-marquee which works on my Vue 3/Node combination. It is a very strange error, maybe related to my setup, not the component itself.

**Comment by EvodiaAut** [comment]
@mickey58github okay then I will close the ticket.
All the best.

**Comment by mickey-bimlive** [comment]
@EvodiaAut - yes, right now I see no other option. Thanks for your help.
