### ISSUE TITLE
Console error for appendChild

### ISSUE THREAD

**Issue by stevenson-digital** [EvodiaAut/vue-marquee-text-component#6]
Hey,

I've come into an issue where on the production environment (Netlify) I'm faced with this console error:

`DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.`

This happens on both Chrome and FireFox. I've debugged the page and found that it's the `<marquee-text>` component that is causing the issue. It doesn't happen locally but if I comment out the marquee component and push to production the console is clear and the page loads correctly.

I've seen some other similar issues regarding Nuxt + Netlify giving this console error; most of these revolve around the use of `v-for` or `v-if` which I am using. I ran a test case to remove the `v-for` from the page but the error persists.

Have you encountered this before?

Thanks,
Ollie :)

**Comment by EvodiaAut** [comment]
Hi @stevenson-digital,

I think that problem is your production environment and not the component.
Now I do not know how can i help you.

Compare your package.json "dependencies" / "devDependencies" maybe you missing a package in production ?

**Comment by stevenson-digital** [comment]
Yeah, I've reached out to them too, I was just trying to see if you had this happen before at all. Everything on the hosting looks to be in order. From other GitHub posts (not related to this plugin) I think it may actually be a larger issue of some specific Nuxt functionality with Netlify static hosting and that unknown specific Nuxt functionality is being used in the plugin which Netlify obviously doesn't seem to handle very well. 

Thanks for replying so quickly.

**Comment by EvodiaAut** [comment]
Sorry i can't help you. :(

**Comment by nonlinearcom** [comment]
Hi @stevenson-digital, did you managed to fix this issue? 
I'm having the problem on Nuxt/Netlify

**Comment by EvodiaAut** [comment]
[Maybe you can find a solution here?](https://github.com/nuxt/nuxt.js/issues/5800)

**Comment by hacknug** [comment]
Wrapping the component with `<ClientOnly>` fixed the issue for me. `vue-marquee-text-component` was already being imported on a client-only plugin.
