### ISSUE TITLE
request pause on hover

### ISSUE THREAD

**Issue by Mellowz** [EvodiaAut/vue-marquee-text-component#7]
i seen about pause, but may marquee pause on hover is another choice

**Comment by EvodiaAut** [comment]
@Mellowz currently I am very busy.
Would it be possible for you to make a pull request?
Alternatively you can wrap it with a div and put the event on the div.
In version 2 it is possible.

**Comment by nasirDoe** [comment]
Script:
`data() {
    return {
      paused: false
   }
}`

Html:
`<marquee-text :repeat="2" :paused="paused">
   <div @mouseenteer="paused = !paused" @mouseleave="paused=false">Content Here</div>
</marquee-text>
`
Worked for me

**Comment by nasirDoe** [comment]
`data() {
    return {
      paused: false,
   }
}

<marquee-text :repeat="2" :paused="paused">
  <div @mouseenter="paused = !paused" @mouseleave="paused = false"></div>
</marquee-text>`

**Comment by initmn** [comment]
Script
`data() {
    return {
      paused: false,
    }
}`

HTML
```
<marquee-text :paused="paused">
   <div  @mouseenter="paused = !paused" @mouseleave="paused = false"></div>
</marquee-text>
```

Worked for me

**Comment by EvodiaAut** [comment]
I wouldn't recommend it because every copied content fires the events.
V 1.2 - Supports then events which are only deposited on the wrapper.
