### ISSUE TITLE
change direction

### ISSUE THREAD

**Issue by lzzfnc** [EvodiaAut/vue-marquee-text-component#8]
is there a simle way to change the scroll direction ? 
thank you : )

**Comment by EvodiaAut** [comment]
hi @lzzfnc 

currently not but you can add `animation-direction: reverse` in the class `.marquee-text-text`  to reverse them or you overwrite the `animation-name: marquee-text-animation`.

in version 2 I will consider this

**Comment by lzzfnc** [comment]
thank you :+1:

**Comment by quiquelhappy** [comment]
can you please update the npm repo with this feature? thanks

**Comment by EvodiaAut** [comment]
I try to close the 2 issues this month.
